#!/usr/bin/env python
# encoding: utf-8

name = "seed_edge"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + X + CH4 <=> H_X + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0009, n=0, Ea=(72000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 1,
    label = "X + OX + CH4 <=> OHX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+18,'cm^5/(mol^2*s)'), n=0.7, Ea=(42000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 2,
    label = "X + OHX + CH4 <=> H2O_X + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(10000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 3,
    label = "X + CO2 <=> CO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 4,
    label = "X + CO <=> OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.84, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 5,
    label = "OX + CX <=> X + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+19,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 6,
    label = "OX + OCX <=> X + CO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+21,'cm^2/(mol*s)'), n=0, Ea=(117600,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 7,
    label = "H_X + CO2X <=> OHX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+19,'cm^2/(mol*s)'), n=0, Ea=(8400,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 8,
    label = "H_X + CH2X <=> X + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 9,
    label = "H_X + CHX <=> X + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 10,
    label = "X + CHX <=> H_X + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 11,
    label = "H2 + CX <=> CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.04, n=0, Ea=(29700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 12,
    label = "X + NH2(D) <=> NH2_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 13,
    label = "X + H <=> H_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 14,
    label = "X + X + NH2NH2 <=> NH2_X + NH2_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 15,
    label = "X + NN.[Pt] <=> NH2_X + NH2_X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 16,
    label = "X + NN[Pt] <=> NH_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(9.18883e+16,'m^2/(mol*s)'), n=0, Ea=(49.335,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 17,
    label = "H_X + NO.[Pt] <=> H2O_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [N-O;Abstracting]
    Euclidian distance = 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -88.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [N-O;Abstracting]
Euclidian distance = 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -88.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 18,
    label = "N2O_X + NH2_X <=> NH_X + [Pt]NN=O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.35926e+17,'m^2/(mol*s)'), n=-0.0183333, Ea=(30.05,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [N=*;*-N-H]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [N=*;*-N-H]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 19,
    label = "NX + NH2NO <=> N2O_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.64967e+15,'m^2/(mol*s)'), n=0.652756, Ea=(120.135,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [N-N;*#N]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [N-N;*#N]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 20,
    label = "X + N=N.[Pt] <=> NH_X + NH_X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.282e+16,'m^2/(mol*s)'), n=0, Ea=(241.213,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
""",
)

entry(
    index = 21,
    label = "NH_X + H2O_X <=> H_X + ON[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.29934e+15,'m^2/(mol*s)'), n=0.652756, Ea=(177.554,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=NH]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 176.9 to 177.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=NH]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 176.9 to 177.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 22,
    label = "NX + [Pt]NN=O <=> N2O_X + NH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.17963e+17,'m^2/(mol*s)'), n=-0.0183333, Ea=(30.05,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*N-N]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*N-N]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
""",
)

entry(
    index = 23,
    label = "NX + [Pt]NN=O <=> N2O_X + NH_X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.17963e+17,'m^2/(mol*s)'), n=-0.0183333, Ea=(30.05,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*N-N]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*N-N]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
""",
)

entry(
    index = 24,
    label = "N2O_X + H2O_X <=> OHX + [Pt]NN=O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.17313e+12,'m^2/(mol*s)'), n=1.13551, Ea=(145.878,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=N]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=N]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 25,
    label = "N2O_X + H2O_X <=> H_X + ON(N=O)[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.29934e+15,'m^2/(mol*s)'), n=0.652756, Ea=(173.381,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=N]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 172.6 to 173.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=N]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 172.6 to 173.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 26,
    label = "NX + N=O.[Pt] <=> N2O_X + H_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.64967e+15,'m^2/(mol*s)'), n=0.652756, Ea=(120.135,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#N]
    Euclidian distance = 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#N]
Euclidian distance = 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 27,
    label = "X + [Pt]NN=O <=> N2O_X + H_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(9.18883e+16,'m^2/(mol*s)'), n=0, Ea=(49.335,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [N;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [N;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 28,
    label = "X + N2 <=> N#N.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 5 used for Adsorbate;VacantSite
    Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 5 used for Adsorbate;VacantSite
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 29,
    label = "X + N2O <=> N2O",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 5 used for Adsorbate;VacantSite
    Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 5 used for Adsorbate;VacantSite
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 30,
    label = "N2O_X + [H][H].[Pt] <=> H_X + [Pt]NN=O",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.29934e+15,'m^2/(mol*s)'), n=0.652756, Ea=(120.135,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=N]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=N]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

